# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.TextField()),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
